# Generated by Django 5.2.3 on 2025-12-15 05:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_activity_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-assigned_date'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='avg_difficulty_rating',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='avg_enjoyment_rating',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='activity',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_motivating',
            field=models.BooleanField(default=False, help_text='True if motivation increased (motivation_after > motivation_before)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='motivation_delta',
            field=models.IntegerField(blank=True, help_text='motivation_after - motivation_before', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='rl_action_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='user_segment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='completed_activities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='overall_session_rating',
            field=models.IntegerField(blank=True, help_text='How was the overall session? (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='session_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='session_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=50),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='total_activities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='total_duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('meditation', 'Meditation'), ('journaling', 'Journaling')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='difficulty_rating',
            field=models.IntegerField(blank=True, help_text='How difficult was this activity? (1=too easy, 5=too hard)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='enjoyment_rating',
            field=models.IntegerField(blank=True, help_text='How much did you enjoy it? (1=hated it, 5=loved it)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='intensity',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='motivation_after',
            field=models.IntegerField(blank=True, help_text='User motivation after completing activity (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='motivation_before',
            field=models.IntegerField(blank=True, help_text='User motivation before starting activity (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, help_text="User's optional notes"),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='completion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
