# Generated by Django 5.2.3 on 2025-07-15 10:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('height', models.FloatField(blank=True, help_text='In centimeters', null=True)),
                ('weight', models.FloatField(blank=True, help_text='In kgs', null=True)),
                ('self_reported_stress', models.PositiveIntegerField(blank=True, help_text='Stress level from 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('gad7_score', models.PositiveIntegerField(help_text='GAD-7 score from 0-21', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)])),
                ('physical_activity_week', models.PositiveIntegerField(help_text='Physical activity level from 0-7 (days a week)', validators=[django.core.validators.MinValueValidator(0)])),
                ('importance_stress_reduction', models.PositiveIntegerField(help_text='Importance of stress reduction from 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('primary_goal', models.PositiveSmallIntegerField(choices=[(0, 'Improve Fitness'), (1, 'Increase Mindfulness'), (2, 'Lose Weight'), (3, 'Reduce Stress')], help_text='Primary goal for using the app')),
                ('workout_goal_days', models.PositiveIntegerField(help_text='Number of days per week you want to work out', validators=[django.core.validators.MinValueValidator(0)])),
                ('segment_label', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'High Anxiety, Low Activity'), (1, 'Moderate Anxiety, Moderate Activity'), (2, 'Low Anxiety, High Activity'), (3, 'Physical Risk'), (4, 'Wellness Seeker'), (5, 'Inactive')], help_text='Segment label based on user profile and activity', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
