# Generated by Django 5.2.3 on 2025-07-15 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gad7_score',
            field=models.PositiveIntegerField(blank=True, help_text='GAD-7 score from 0-21', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='importance_stress_reduction',
            field=models.PositiveIntegerField(blank=True, help_text='Importance of stress reduction from 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='physical_activity_week',
            field=models.PositiveIntegerField(blank=True, help_text='Physical activity level from 0-7 (days a week)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='primary_goal',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Improve Fitness'), (1, 'Increase Mindfulness'), (2, 'Lose Weight'), (3, 'Reduce Stress')], help_text='Primary goal for using the app', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='workout_goal_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days per week you want to work out', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
