# Generated by Django 5.2.3 on 2026-01-27 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rl_agent_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_activities_completed', models.PositiveIntegerField(default=0)),
                ('total_activities_assigned', models.PositiveIntegerField(default=0)),
                ('total_exercises', models.PositiveIntegerField(default=0)),
                ('total_meditations', models.PositiveIntegerField(default=0)),
                ('total_journaling', models.PositiveIntegerField(default=0)),
                ('current_streak_days', models.PositiveIntegerField(default=0, help_text='Consecutive days with completed activities')),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('avg_motivation_improvement', models.FloatField(default=0.0, help_text='Average motivation delta across activities')),
                ('avg_enjoyment_rating', models.FloatField(default=0.0)),
                ('avg_difficulty_rating', models.FloatField(default=0.0)),
                ('total_minutes_exercised', models.PositiveIntegerField(default=0)),
                ('total_minutes_meditated', models.PositiveIntegerField(default=0)),
                ('activities_this_week', models.PositiveIntegerField(default=0)),
                ('minutes_this_week', models.PositiveIntegerField(default=0)),
                ('activities_this_month', models.PositiveIntegerField(default=0)),
                ('minutes_this_month', models.PositiveIntegerField(default=0)),
                ('overall_completion_rate', models.FloatField(default=0.0, help_text='Percentage of assigned activities completed')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Statistics',
                'verbose_name_plural': 'User Statistics',
            },
        ),
    ]
