# Generated by Django 5.2.3 on 2026-03-12 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userstatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gad7_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='importance_stress_reduction',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='physical_activity_week',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='self_reported_stress',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='weight',
        ),
        migrations.AddField(
            model_name='customuser',
            name='diet_type',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('balanced', 'Balanced'), ('junk_food', 'Junk Food'), ('keto', 'Keto')], help_text="User's dietary preference", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='happiness_score',
            field=models.PositiveIntegerField(blank=True, help_text='Self-reported happiness score (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mental_health_condition',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('ptsd', 'PTSD'), ('depression', 'Depression'), ('anxiety', 'Anxiety'), ('bipolar', 'Bipolar')], help_text='Mental health condition', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='screen_time_per_day',
            field=models.FloatField(blank=True, help_text='Screen time per day in hours (0-24)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='self_reported_social_interaction_score',
            field=models.PositiveIntegerField(blank=True, help_text='Social interaction score (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sleep_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Average sleep hours per night (0-9)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stress_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], help_text='Self-reported stress level', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_hours_per_week',
            field=models.PositiveIntegerField(blank=True, help_text='Work hours per week (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='workout_goal_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days per week you want to work out', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
