# Generated by Django 5.2.3 on 2026-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_gad7_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exercise_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], help_text='Exercise level', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='segment_label',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Older High Stress Exhausted'), (1, 'Young High Stress Active Social'), (2, 'Mid Life Low Stress Depressed'), (3, 'Mid Life Thriving Wellness Seeker'), (4, 'Working Professional Sedentary Stable')], help_text='Segment label based on user profile and activity', null=True),
        ),
    ]
