MOTIVATIONAL_QUOTES = [
    ("A calm breath is a small reset you can take anywhere.", ""),
    ("Tiny healthy choices become visible strength over time.", ""),
    ("Progress grows faster when you stop waiting for perfect days.", ""),
    ("A short walk still counts as care for your future self.", ""),
    ("Rest is not retreat; it is part of the training plan.", ""),
    ("Consistency beats intensity when you are building a better life.", ""),
    ("You do not need a new mood to begin; action can create momentum.", ""),
    ("Hydration, movement, and sleep solve more than they get credit for.", ""),
    ("One grounded choice can change the direction of a whole day.", ""),
    ("You are allowed to grow slowly and still call it growth.", ""),
    ("The next helpful step matters more than the perfect long-term plan.", ""),
    ("Energy returns in layers; protect the habits that refill it.", ""),
    ("Self-respect is often built from ordinary promises kept quietly.", ""),
    ("You can start again without calling the last attempt a failure.", ""),
    ("A five-minute reset is better than a zero-minute ideal.", ""),
    ("Your body responds to kindness faster than it responds to shame.", ""),
    ("Momentum often begins with a single honest check-in.", ""),
    ("The day does not need to be easy for it to be meaningful.", ""),
    ("Healthy routines look small while they are forming and powerful later.", ""),
    ("You can protect your peace and still keep moving forward.", ""),
    ("A steady routine can carry you when motivation is late.", ""),
    ("The best reset is usually simple: breathe, drink water, move, continue.", ""),
    ("Even low-energy effort is still effort worth respecting.", ""),
    ("Your future self benefits from the boring basics you do today.", ""),
    ("It is easier to trust yourself after one completed promise.", ""),
    ("Wellness is often quiet, repetitive, and completely worth it.", ""),
    ("Good habits become easier when you stop asking them to be dramatic.", ""),
    ("Care is not always visible, but it is always cumulative.", ""),
    ("The most powerful routine is the one you can repeat tomorrow.", ""),
    ("You do not need to catch up all at once; you need a workable next step.", ""),
    ("Gentle structure can reduce the noise in a difficult day.", ""),
    ("A clear mind often starts with a cared-for body.", ""),
    ("Your recovery deserves the same discipline as your goals.", ""),
    ("Small acts of self-respect build strong foundations.", ""),
    ("There is strength in slowing down before you burn out.", ""),
    ("A journal entry can carry weight that your mind should not carry alone.", ""),
    ("The routine that looks modest now may be your breakthrough later.", ""),
    ("You are easier to help when you tell the truth about how you feel.", ""),
    ("Sleep is not wasted time; it is maintenance for every system you rely on.", ""),
    ("A better day can begin in the middle of the current one.", ""),
    ("You do not have to feel confident to do something useful.", ""),
    ("Stability is built from repeated basics, not rare heroic effort.", ""),
    ("When the day feels heavy, lower the bar and keep the pattern alive.", ""),
    ("A kinder inner voice can change the quality of your effort.", ""),
    ("Well-being improves when you work with your limits instead of denying them.", ""),
    ("The habit you repeat under stress is the one that shapes you.", ""),
    ("You can make today useful without making it perfect.", ""),
    ("Quiet discipline is still discipline.", ""),
    ("Every return to your routine is evidence that you are not giving up.", ""),
    ("A balanced day usually comes from balanced choices, not lucky timing.", ""),
    ("Taking care of your mind is productive work.", ""),
    ("Your next breath is already a chance to reset your pace.", ""),
    ("A short stretch can interrupt a long spiral.", ""),
    ("Healthy momentum likes clear plans and low friction.", ""),
    ("The simplest healthy action is often the right one to start with.", ""),
    ("Build routines that support the version of you who is tired too.", ""),
    ("You are allowed to need support and still be strong.", ""),
    ("The body keeps honest records; treat it like an ally.", ""),
    ("Being overwhelmed is a signal to simplify, not a verdict on your ability.", ""),
    ("A walk outside can change the texture of a hard hour.", ""),
    ("Steady healing often looks ordinary in the moment.", ""),
    ("The next healthy choice does not need permission from the last bad one.", ""),
    ("Your habits are strongest when they are designed for real life.", ""),
    ("You can lower pressure without lowering your standards forever.", ""),
    ("Mental clarity often follows physical care more than mental force.", ""),
    ("Routine is a quiet form of self-trust.", ""),
    ("Showing up gently is better than disappearing completely.", ""),
    ("The goal is not to never wobble; the goal is to return faster.", ""),
    ("A little structure can make difficult emotions easier to hold.", ""),
    ("You are building evidence that you can care for yourself well.", ""),
    ("The basics are powerful because they keep working.", ""),
    ("A strong routine makes hard days less expensive.", ""),
    ("You do not have to win the whole day to improve it.", ""),
    ("Small recovery habits protect long-term performance.", ""),
    ("The most reliable motivation often appears after starting, not before.", ""),
    ("Give your nervous system something predictable to lean on.", ""),
    ("Movement can clear thoughts that overthinking only tightens.", ""),
    ("Taking one useful action can make fear less convincing.", ""),
    ("The routine you can repeat in stress is the routine that counts.", ""),
    ("A better pace is sometimes the smartest productivity tool.", ""),
    ("A little sunlight and a little movement can shift a lot.", ""),
    ("Wellness grows when you make the healthy option easier to begin.", ""),
    ("Your body notices patterns even when your mood does not.", ""),
    ("Repair is progress too.", ""),
    ("The pause before a reaction can be a powerful kind of strength.", ""),
    ("A real plan includes water, sleep, movement, and room to recover.", ""),
    ("You can feel off and still do something supportive for yourself.", ""),
    ("A stable foundation is made from repeated ordinary care.", ""),
    ("Your effort still matters on the days nobody sees it.", ""),
    ("Try making the next choice lighter instead of making yourself harder.", ""),
    ("Self-compassion makes consistency easier to sustain.", ""),
    ("Health improves when your systems are simple enough to survive busy days.", ""),
    ("If the plan is too heavy to carry today, make it smaller and carry it anyway.", ""),
    ("You can rebuild rhythm one ordinary hour at a time.", ""),
    ("The strongest routine is the one that welcomes imperfect days.", ""),
    ("You do not need to punish yourself into becoming disciplined.", ""),
    ("Even a brief journal note can turn confusion into useful information.", ""),
    ("Keep the promise small enough that you can keep it under stress.", ""),
    ("A resilient day usually begins with a realistic morning.", ""),
    ("Focus on what helps your next hour, not just your next month.", ""),
    ("A simple routine can be a form of relief.", ""),
    ("Make recovery visible in your schedule, not just in your intentions.", ""),
    ("Healthy momentum is easier when guilt is not driving the vehicle.", ""),
    ("You can respect your limits without surrendering your progress.", ""),
    ("The next kind decision toward yourself is worth taking seriously.", ""),
    ("A measured pace can carry you farther than a reckless sprint.", ""),
    ("Wellness gets stronger when you repeat what works instead of chasing novelty.", ""),
    ("Your recovery habits are part of your ambition, not separate from it.", ""),
    ("Keep the pattern, even if you reduce the volume.", ""),
    ("What you practice daily becomes what supports you automatically.", ""),
    ("A few honest minutes of reflection can save hours of confusion.", ""),
    ("There is no wasted day that includes one act of real care.", ""),
    ("Choose the habit that future-you will quietly thank you for.", ""),
    ("Healthy systems win by being repeatable.", ""),
    ("Sometimes the bravest plan is the sustainable one.", ""),
]