# Generated by Django 5.2.3 on 2026-03-14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('reflection', 'Reflection'),
                            ('gratitude', 'Gratitude'),
                            ('stress', 'Stress Processing'),
                            ('goals', 'Goals and Direction'),
                            ('self_compassion', 'Self Compassion'),
                        ],
                        default='reflection',
                        max_length=30,
                    ),
                ),
                ('prompt_text', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JournalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                (
                    'mood',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'Very Low'),
                            (2, 'Low'),
                            (3, 'Neutral'),
                            (4, 'Good'),
                            (5, 'Great'),
                        ],
                        default=3,
                        help_text='How you felt while writing this entry (1-5)',
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='journal_entries',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='journal.journaltag')),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'entry_date'], name='journal_jou_user_id_e10dd8_idx'),
                    models.Index(fields=['user', 'mood'], name='journal_jou_user_id_346a42_idx'),
                    models.Index(fields=['user', 'is_favorite'], name='journal_jou_user_id_c0f850_idx'),
                    models.Index(fields=['user', 'is_archived'], name='journal_jou_user_id_a95db4_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='JournalReadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('manual', 'Manual Open'),
                            ('recommendation', 'Recommended Reread'),
                            ('reflection', 'Reflection Session'),
                        ],
                        default='manual',
                        max_length=20,
                    ),
                ),
                ('read_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'entry',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='read_events',
                        to='journal.journalentry',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='journal_read_events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-read_at'],
                'indexes': [
                    models.Index(fields=['user', 'read_at'], name='journal_jou_user_id_febff4_idx'),
                    models.Index(fields=['entry', 'read_at'], name='journal_jou_entry_i_2f6b90_idx'),
                ],
            },
        ),
    ]
