# Generated by Django 5.2.3 on 2026-03-14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_seed_journal_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='situation',
            field=models.TextField(
                blank=True,
                default='',
                help_text='What happened? Briefly describe the triggering event or context.',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='automatic_thought',
            field=models.TextField(
                blank=True,
                default='',
                help_text='What went through your mind? Write the automatic thought word-for-word.',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='emotion_intensity_before',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                help_text='How intense is the emotion right now? (0 = none, 100 = maximum)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='cognitive_distortions',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Identified cognitive distortions as a JSON list of keys.',
            ),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='evidence_for',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Facts that support the automatic thought.',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='evidence_against',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Facts that challenge or contradict the automatic thought.',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='balanced_thought',
            field=models.TextField(
                blank=True,
                default='',
                help_text='A more balanced or realistic alternative to the automatic thought.',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='emotion_intensity_after',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                help_text='How intense is the emotion after reframing? (0 = none, 100 = maximum)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='behavioral_response',
            field=models.TextField(
                blank=True,
                default='',
                help_text='What action will you take based on this reflection?',
            ),
            preserve_default=False,
        ),
    ]
