# Generated by Django 5.2.3 on 2026-03-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_seed_journal_prompts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journal_jou_user_id_467e88_idx',
            old_name='journal_jou_user_id_e10dd8_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journal_jou_user_id_8668cb_idx',
            old_name='journal_jou_user_id_346a42_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journal_jou_user_id_a2ab11_idx',
            old_name='journal_jou_user_id_c0f850_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journal_jou_user_id_af40d4_idx',
            old_name='journal_jou_user_id_a95db4_idx',
        ),
        migrations.RenameIndex(
            model_name='journalreadevent',
            new_name='journal_jou_user_id_956fcf_idx',
            old_name='journal_jou_user_id_febff4_idx',
        ),
        migrations.RenameIndex(
            model_name='journalreadevent',
            new_name='journal_jou_entry_i_fd066c_idx',
            old_name='journal_jou_entry_i_2f6b90_idx',
        ),
    ]
