# Generated by Django 5.2.3 on 2026-03-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_journal_jou_user_id_e10dd8_idx_journal_jou_user_id_467e88_idx_and_more'),
        ('journal', '0004_seed_cbt_prompts'),
    ]

    operations = [
    ]
