# Generated by Django 5.2.3 on 2026-03-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_merge_20260314_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalprompt',
            name='category',
            field=models.CharField(choices=[('reflection', 'Reflection'), ('gratitude', 'Gratitude'), ('stress', 'Stress Processing'), ('goals', 'Goals and Direction'), ('self_compassion', 'Self Compassion'), ('thought_record', 'CBT Thought Record')], default='reflection', max_length=30),
        ),
    ]
