services:
  web:
    build: .
    container_name: wellness_application
    ports:
      - "8000:8000"
    volumes:
      - .:/wellnessapp
    command: >
      bash -c "python manage.py makemigrations --noinput &&
               python manage.py migrate --noinput &&
               python manage.py flood_motivational_quotes &&
               python manage.py create_startup_notifications &&
               python manage.py runserver 0.0.0.0:8000"
  chatbot:
    build: ./RAG-WellnessApp
    container_name: wellness_chatbot
    ports:
      - "7999:7999"
    volumes:
      - ./RAG-WellnessApp/knowledge_base:/app/knowledge_base
      - ./RAG-WellnessApp/vectorstore:/app/vectorstore
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
